// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SeleniumSpecflowTest.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("AddCourse")]
    public partial class AddCourseFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "AddCourse.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "AddCourse", "\tIn order to book a course\r\n\tAs a user\r\n\tI want to add course(s) into the cart", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add a course by specific course information")]
        public virtual void AddACourseBySpecificCourseInformation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add a course by specific course information", null, ((string[])(null)));
#line 8
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
 testRunner.Given("I have navigated to home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
 testRunner.And("I click cart link and go to booking page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.When("I click add course link on booking page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 12
 testRunner.And("I select a course \'ISTQB Foundation Certificate\' on booking page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.And("I select a delivery location \'Sydney\' on booking page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.And("I select option 1 in start date on booking page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
 testRunner.And("I click add course button on booking page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
 testRunner.Then("the booked course title should be \'ISTQB Foundation Certificate\' on booking page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 17
 testRunner.And("the booked delivery location should be \'Sydney\' on booking page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
 testRunner.And("the booked start date should be first option on booking page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("All available courses can be added into cart")]
        [NUnit.Framework.TestCaseAttribute("Complete Tester (Course Bundle)", null)]
        [NUnit.Framework.TestCaseAttribute("ISTQB Foundation Certificate", null)]
        [NUnit.Framework.TestCaseAttribute("ISTQB Usability Tester Certificate", null)]
        [NUnit.Framework.TestCaseAttribute("ISTQB Advanced Test Analyst Certificate", null)]
        [NUnit.Framework.TestCaseAttribute("ISTQB Advanced Test Manager Certificate", null)]
        [NUnit.Framework.TestCaseAttribute("ISTQB Advanced Technical Test Analyst Certificate", null)]
        [NUnit.Framework.TestCaseAttribute("ISTQB Advanced Test Automation Engineer Certificate", null)]
        [NUnit.Framework.TestCaseAttribute("ISTQB Advanced Security Tester Certificate", null)]
        [NUnit.Framework.TestCaseAttribute("ASTQB Mobile Testing Certificate", null)]
        [NUnit.Framework.TestCaseAttribute("TMMi Professional Certificate", null)]
        [NUnit.Framework.TestCaseAttribute("iSQI Scrum Master Pro Certification", null)]
        [NUnit.Framework.TestCaseAttribute("ISTQB Foundation Agile Tester Extension", null)]
        [NUnit.Framework.TestCaseAttribute("iSQI Certified Agile Essentials", null)]
        [NUnit.Framework.TestCaseAttribute("iSQI Certified Agile Business Analysis", null)]
        [NUnit.Framework.TestCaseAttribute("Leading SAFe Certification", null)]
        [NUnit.Framework.TestCaseAttribute("SAFe for Teams Certification", null)]
        [NUnit.Framework.TestCaseAttribute("SAFe DevOps Certification", null)]
        [NUnit.Framework.TestCaseAttribute("BCS Business Analysis Foundation Certificate", null)]
        [NUnit.Framework.TestCaseAttribute("BCS Requirements Engineering Certificate", null)]
        [NUnit.Framework.TestCaseAttribute("BCS Modelling Business Processes Certificate", null)]
        [NUnit.Framework.TestCaseAttribute("BCS Business Analysis Practice Certificate", null)]
        [NUnit.Framework.TestCaseAttribute("User Acceptance Testing (UAT)", null)]
        [NUnit.Framework.TestCaseAttribute("Professional Testing Processes", null)]
        [NUnit.Framework.TestCaseAttribute("Risk Based Testing", null)]
        [NUnit.Framework.TestCaseAttribute("Test Team Leadership", null)]
        [NUnit.Framework.TestCaseAttribute("DASA DevOps Fundamentals Certification", null)]
        public virtual void AllAvailableCoursesCanBeAddedIntoCart(string courseName, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("All available courses can be added into cart", null, exampleTags);
#line 22
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 23
 testRunner.Given("I have navigated to home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 24
 testRunner.And("I click cart link and go to booking page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 25
 testRunner.When("I click add course link on booking page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 26
 testRunner.And(string.Format("I select a course {0} from example on booking page", courseName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
 testRunner.And("I select option 1 in delivery location on booking page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 28
 testRunner.And("I select option 1 in start date on booking page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
 testRunner.And("I click add course button on booking page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
 testRunner.Then(string.Format("the booked course title should be {0} from example on booking page", courseName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 31
 testRunner.When("I click remove course link on booking page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 32
 testRunner.Then("no course should be added on booking page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion

